### ISSUE TITLE
Add license information to the yaml file header

### ISSUE THREAD

**Issue by larsbarring** [clix-meta/clix-meta#118]
The yaml files should contain a brief reference to the clix-meta license. Currently the top few lines reads
``` yaml
# These index definitions are auto-generated from the master table at
# https://github.com/clix-meta/clix-meta
---
distribution:
  name: clix-meta
  version: 0.6.1
indices:
``` 

This should be changed to something like this:
``` yaml
# This file is part of the Clix-meta project at https://github.com/clix-meta/clix-meta
# It is distributed under the Creative Commons Attribution-ShareAlike 4.0 International License.
# These index definitions are auto-generated from the master table
---
distribution:
  name: clix-meta
  version: 0.6.1
indices:
``` 
But the exact wording needs to be refined.
