### ISSUE TITLE
Improve yaml representation of placeholders

### ISSUE THREAD

**Issue by zklaus** [clix-meta/clix-meta#31]
In #20, @aulemahal brought up the following issue:

> When parameters are not set, but only described, it looks like:
```yaml
parameters:
  threshold:
    kind: quantity
    standard_name: air_temperature
    data: {TT}
    units: "degree_Celsius"
```
> However, when loading this, we get a dictionary where 'data': {'TT': None}, whereas I expected 'data': '{TT}'. I think the correct yaml would need protecting quotes:
```yaml
parameters:
  threshold:
    kind: quantity
    standard_name: air_temperature
    data: "{TT}"
    units: "degree_Celsius"
```
