### ISSUE TITLE
Definition of TG(10|90)p indices is invalid as per ECAD specification

### ISSUE THREAD

**Issue by abel-bzz** [clix-meta/clix-meta#62]
# Please explain briefly what is wrong

This is a bit nitpicking because TG10p and TG90p are the only members `Txxxp` family that **are part** of ECAD and **not part** of ETCCDI. And I suspect this is the source of this issue. 
The yaml file properly shows the reference specification with `reference: ECA&D` for TG10p and TG90p  and `reference: ETCCDI` for the 4 others.
However, according to ECAD, Txxxp should be outputted as a number of days but, in ETCCDI they should be a percentage of days.
Thus, in the yaml file, as illustrated below, TG10p and TG90p `long_name` and `units` are coherent with the 4 others but are incoherent with their own reference.

I feel like the two units could be accepted for the same index name, in icclim we leave the choice open to the user (default is number of days).

Q: Would a syntax like `units: % | days` and `long_name: {Percentage of} days when Tmean < 10th percentile`  be valid in clix-meta/cf/cmip ?
It would be a _dynamic_ specification that a program computing the index would need to modify according to its parameters.

<details>
   <summary>TG10p and TN90p yaml (click me)</summary>

  ```
    tg10p:
      reference: ECA&D
      period:
        allowed:
          annual:
        default: annual
      output:
        var_name: "tg10p"
        standard_name:
        long_name: "Percentage of days when Tmean < 10th percentile"
        units: "%"
        cell_methods:
      input:
        data: tas
      index_function:
        name: count_percentile_occurrences
        parameters:
          percentile:
            kind: quantity
            standard_name:
            proposed_standard_name: quantile
            data: 10
            units: "%"
          condition:
            kind: operator
            operator: "<"

  tn90p:
    reference: ETCCDI
    period:
      allowed:
        annual:
      default: annual
    output:
      var_name: "tn90p"
      standard_name:
      long_name: "Percentage of days when Tmin > 90th percentile"
      units: "%"
      cell_methods:
    input:
      data: tasmin
    index_function:
      name: count_percentile_occurrences
      parameters:
        percentile:
          kind: quantity
          standard_name:
          proposed_standard_name: quantile
          data: 90
          units: "%"
        condition:
          kind: operator
          operator: ">"
    ET:
      short_name: "tn90p"
      long_name: "WMO No.1500: Warm nights (count of days)"
      definition: "Number of days when TN > 90th percentile"
      comment:
  ```

</details>
