### ISSUE TITLE
Conversion of table column PARAMETER_definition to yaml is not correct for r{PRC}pDAYS

### ISSUE THREAD

**Issue by larsbarring** [clix-meta/clix-meta#72]
The table entry reads (with linebreaks added):

```
data_threshold: (var_name: threshold, 
                           standard_name: lwe_precipitation_rate, 
                           value: 1, 
                           unit: mm day-1, 
                           long_name: “Wet day threshold”), 
data_condition: >=, 
percentile: (var_name: percentile, 
                   standard_name: , 
                   proposed_standard_name: quantile, 
                   value: {PRC}, 
                   unit: %, 
                   long_name: “Percentile value”), 
percentile_condition: >
```

and the resulting yam file entry reads:

``` yaml
      name: count_thresholded_percentile_occurrences
      parameters:
        data_threshold:
          kind: quantity
          standard_name: lwe_precipitation_rate
          long_name: "Wet day threshold"
          data: 1
          units: "mm day-1"
        data_condition:
          kind: operator
          operator: ">"
        percentile:
          kind: quantity
          standard_name:
          proposed_standard_name: quantile
          long_name: "Percentile value"
          data: "{PRC}"
          units: "%"
        percentile_condition:
          kind: operator
          operator: ">"
```

Note that the `data_condition` is changed from **>=** to **>**
